[package]
name = "rust-edit"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

gtk = { version = "*"}
pango = "*"
pangocairo = "*"